// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
export const parser = LRParser.deserialize({
  version: 14,
  states: "&lQYQPOOOkQPO'#CsO!PQPO'#CeO!UQPO'#CnO!ZQPO'#CpOOQO'#Cd'#CdO!fQPO'#CrO!wQPO'#C`OOQO'#C`'#C`OOQO'#C_'#C_Q#]QPO'#C_OOQO'#Cw'#CwQYQPOOOOQO,58|,58|O!ZQPO,59PO!ZQPO,59YO#bQQO'#CiO!ZQPO'#ClOOQO'#Ch'#ChO$hQQO'#CgOOQO,59[,59[OOQO'#Cu'#CuO$xQPO'#CtOOQO,59^,59^OOQO'#Cs'#CsOOQO,58{,58{OOQO,58y,58yOOQO-E6u-E6uOOQO1G.k1G.kOOQO1G.t1G.tOOQO'#Cj'#CjOOQO,59T,59TO%TQPO,59WOOQO'#Cm'#CmO!ZQPO'#CxO%YQQO,59RO!ZQPO'#CyO%jQPO,59`OOQO1G.r1G.rOOQO,59d,59dOOQO-E6v-E6vOOQO,59e,59eOOQO-E6w-E6w",
  stateData: "%{~OpOSPOS~OVPOYQOcROeSOjXO~Oq]OVgX_gXjgXngXtgX~OV^O~OV_O~OV`O_bOtaO~OV`O_bOtaOjfXnfX~OVhOYQOcROeSOjSXnSX~OjjO~OrnOsnOj]Xn]Xv]Xw]Xx]Xy]Xz]X{]Xu]X~OvqOwqOxqOyqOzqO~OjZXnZX{ZXuZX~P$VO{tOjhXnhX~OuvO~OjZanZa{ZauZa~P$VO{tOjhanha~OYceVe~",
  goto: "#znPPPosw{P!P!WP!]!m!x#RP!x#U!WP!WP!P#Y#_#bP#h#n#tTZO[TYO[TWO[TVO[SWO[RiVVTOV[QdSSeUtQl^Qm_Rpa[cSU^_atRwr_bSU^_artRo`TrcsVUOV[RgUQfURytQ[ORk[QscRxsQufRzu",
  nodeNames: "⚠ LineComment Program Line Statement LabeledStatement LabelDef Identifier DirectiveStmt EquStmt EquDir Expression ExprAtom LabelRef Suffix Number ParenExpr Operator MemStmt MemDir OrgStmt OrgDir InstructionStmt OpcodeName OperandList Operand LineBreak",
  maxTerm: 43,
  skippedNodes: [0,1],
  repeatNodeCount: 3,
  tokenData: ",[~RrXY#]YZ#h]^#mpq#]st#sxy#xyz#}z{$S{|$X|}$^}!O$c!O!P$q!P!Q&X!Q!R%P!R![%b![!]&^!]!^&c!c!g&n!g!h'P!h!o&n!o!p(p!p!q&n!q!r*a!r!}&n#Q#R,Q#R#S&n#T#X&n#X#Y'P#Y#a&n#a#b(p#b#c&n#c#d*a#d#o&n#p#q,V~#bQp~XY#]pq#]~#mOj~~#pPYZ#h~#xOs~~#}Ot~~$SOu~~$XOx~~$^Ov~~$cO{~R$hRwQ!O!P$q!Q!R%P!R![%bP$tP!Q![$wP$|P_P!Q![$wP%US_P!O!P$q!Q![%b!z!{%m#l#m%mP%gQ_P!O!P$q!Q![%bP%pR!Q![%y!c!i%y#T#Z%yP&OR_P!Q![%y!c!i%y#T#Z%y~&^Oy~~&cOq~~&hQP~YZ&c#Q#R&c~&sSV~!Q![&n!c!}&n#R#S&n#T#o&n~'UWV~!Q![&n!c!s&n!s!t'n!t!}&n#R#S&n#T#e&n#e#f'n#f#o&n~'sWV~!Q![&n!c!w&n!w!x(]!x!}&n#R#S&n#T#i&n#i#j(]#j#o&n~(dSY~V~!Q![&n!c!}&n#R#S&n#T#o&n~(uWV~!Q![&n!c!g&n!g!h)_!h!}&n#R#S&n#T#X&n#X#Y)_#Y#o&n~)dWV~!Q![&n!c!o&n!o!p)|!p!}&n#R#S&n#T#a&n#a#b)|#b#o&n~*TSc~V~!Q![&n!c!}&n#R#S&n#T#o&n~*fWV~!Q![&n!c!t&n!t!u+O!u!}&n#R#S&n#T#f&n#f#g+O#g#o&n~+TWV~!Q![&n!c!i&n!i!j+m!j!}&n#R#S&n#T#Z&n#Z#[+m#[#o&n~+tSe~V~!Q![&n!c!}&n#R#S&n#T#o&n~,VOr~~,[Oz~",
  tokenizers: [0, 1],
  topRules: {"Program":[0,2]},
  tokenPrec: 221
})
