// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
export const parser = LRParser.deserialize({
  version: 14,
  states: "%pQYQPOOOeQPO'#CnOyQPO'#CdO!UQPO'#CmO!gQPO'#C`OOQO'#C`'#C`OOQO'#C_'#C_Q!uQPO'#C_OOQO'#Cr'#CrQYQPOOOOQO,58|,58|O!zQQO'#ChOyQPO'#CkOOQO'#Cg'#CgO#lQQO'#CfOOQO,59O,59OOOQO'#Cp'#CpO$WQPO'#CoOOQO,59X,59XOOQO'#Cn'#CnOOQO,58{,58{OOQO,58y,58yOOQO-E6p-E6pOOQO'#Ci'#CiOOQO,59S,59SO$cQPO,59VOOQO'#Cl'#ClOyQPO'#CsO$hQQO,59QOyQPO'#CtO%SQPO,59ZOOQO1G.q1G.qOOQO,59_,59_OOQO-E6q-E6qOOQO,59`,59`OOQO-E6r-E6r",
  stateData: "%b~OkOSPOS~OVPOXQOeUO~OlYOVbX^bXebXibXobX~OVZO^]Oo[O~OVZO^]Oo[OeaXiaX~OVcOXQOeSXiSX~OeeO~OmgOngOe[Xi[Xq[Xr[Xs[Xt[Xu[Xp[X~OqjOrjOsjOtjOeYXiYXuYXpYX~OumOecXicX~OpoO~OqjOrjOsjOtjOeYaiYauYapYa~OumOecaica~OXV~",
  goto: "#fiPPPjnrvPzP!R!]!f!mP!f!pz!t!y!|P#S#Y#`TWOXTVOXTTOXTSOXSTOXRdSQ_QS`RmRi[W^QR[mRpkZ]QR[kmRhZTk^lVROSXRbRQaRRrmQXORfXQl^RqlQnaRsn",
  nodeNames: "⚠ LineComment Program Line Statement LabeledStatement LabelDef Identifier DirectiveStmt Directive Expression ExprAtom LabelRef Suffix Number ParenExpr Operator InstructionStmt OpcodeName OperandList Operand LineBreak",
  maxTerm: 37,
  skippedNodes: [0,1],
  repeatNodeCount: 3,
  tokenData: "+[~RqXY#YYZ#e]^#jpq#Yst#pxy#uyz#zz{$P{|$U|}$Z}!O$`!O!P$n!P!Q&U!Q!R$|!R![%_![!]&Z!]!^&`!c!g&k!g!h&|!h!o&k!o!p(m!p!q&k!q!r)y!r!}&k#Q#R+V#R#S&k#T#X&k#X#Y&|#Y#a&k#a#b(m#b#c&k#c#d)y#d#o&k~#_Qk~XY#Ypq#Y~#jOe~~#mPYZ#e~#uOn~~#zOo~~$POp~~$UOs~~$ZOq~~$`Ou~R$eRrQ!O!P$n!Q!R$|!R![%_P$qP!Q![$tP$yP^P!Q![$tP%RS^P!O!P$n!Q![%_!z!{%j#l#m%jP%dQ^P!O!P$n!Q![%_P%mR!Q![%v!c!i%v#T#Z%vP%{R^P!Q![%v!c!i%v#T#Z%v~&ZOt~~&`Ol~~&eQP~YZ&`#Q#R&`~&pSV~!Q![&k!c!}&k#R#S&k#T#o&k~'RWV~!Q![&k!c!s&k!s!t'k!t!}&k#R#S&k#T#e&k#e#f'k#f#o&k~'pWV~!Q![&k!c!w&k!w!x(Y!x!}&k#R#S&k#T#i&k#i#j(Y#j#o&k~(aSX~V~!Q![&k!c!}&k#R#S&k#T#o&k~(rWV~!Q![&k!c!g&k!g!h)[!h!}&k#R#S&k#T#X&k#X#Y)[#Y#o&k~)aWV~!Q![&k!c!o&k!o!p(Y!p!}&k#R#S&k#T#a&k#a#b(Y#b#o&k~*OWV~!Q![&k!c!t&k!t!u*h!u!}&k#R#S&k#T#f&k#f#g*h#g#o&k~*mWV~!Q![&k!c!i&k!i!j(Y!j!}&k#R#S&k#T#Z&k#Z#[(Y#[#o&k~+[Om~",
  tokenizers: [0, 1],
  topRules: {"Program":[0,2]},
  tokenPrec: 199
})
